### ISSUE TITLE
Odhlašování nefunguje

### ISSUE THREAD

**Issue by filip-hejsek** [krulis-martin/quixam#1]
V případě přihlášení přes CAS není možné se úplně odhlásit. Po odhlášení zůstane `CasAuthenticator` stále přihlášený a při příštím kliknutí na `Přihlásit pomocí externí autentizace` dojde k přihlášení bez zadávání hesla. Kvůli tomu není možné se důkladně odhlásit jinak, než smazáním cookies.

Chyba je v tom, že se nikde nevolá `CasAuthenticator->logout`, takže přihlášení zůstává aktivní.

**Comment by krulis-martin** [comment]
Solved and deployed.
